// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_FedoraRemixWSLUI_0_H
#define WINRT_FedoraRemixWSLUI_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::FedoraRemixWSLUI
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::FedoraRemixWSLUI::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::FedoraRemixWSLUI::MainPage>{ using type = class_category; };
    template <> struct category<winrt::FedoraRemixWSLUI::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::FedoraRemixWSLUI::MainPage> = L"FedoraRemixWSLUI.MainPage";
    template <> inline constexpr auto& name_v<winrt::FedoraRemixWSLUI::XamlMetaDataProvider> = L"FedoraRemixWSLUI.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::FedoraRemixWSLUI::IMainPage> = L"FedoraRemixWSLUI.IMainPage";
    template <> inline constexpr guid guid_v<winrt::FedoraRemixWSLUI::IMainPage>{ 0x791C5146,0x8BDC,0x50F5,{ 0x97,0x3B,0x80,0xDB,0x63,0xB5,0x12,0x3A } }; // 791C5146-8BDC-50F5-973B-80DB63B5123A
    template <> struct default_interface<winrt::FedoraRemixWSLUI::MainPage>{ using type = winrt::FedoraRemixWSLUI::IMainPage; };
    template <> struct default_interface<winrt::FedoraRemixWSLUI::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::FedoraRemixWSLUI::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_FedoraRemixWSLUI_IMainPage
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::FedoraRemixWSLUI::IMainPage>
    {
        template <typename D> using type = consume_FedoraRemixWSLUI_IMainPage<D>;
    };
}
#endif
