// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_FedoraRemixWSLUI_1_H
#define WINRT_FedoraRemixWSLUI_1_H
#include "winrt/impl/FedoraRemixWSLUI.0.h"
WINRT_EXPORT namespace winrt::FedoraRemixWSLUI
{
    struct __declspec(empty_bases) IMainPage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMainPage(IMainPage const&) noexcept = default;
        IMainPage(IMainPage&&) noexcept = default;
        IMainPage& operator=(IMainPage const&) & noexcept = default;
        IMainPage& operator=(IMainPage&&) & noexcept = default;
    };
}
#endif
