// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_Devices_Sms_1_H
#define WINRT_Windows_Devices_Sms_1_H
#include "winrt/impl/Windows.Devices.Sms.0.h"
WINRT_EXPORT namespace winrt::Windows::Devices::Sms
{
    struct __declspec(empty_bases) ISmsAppMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsAppMessage>,
        impl::require<winrt::Windows::Devices::Sms::ISmsAppMessage, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsAppMessage(std::nullptr_t = nullptr) noexcept {}
        ISmsAppMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsAppMessage(ISmsAppMessage const&) noexcept = default;
        ISmsAppMessage(ISmsAppMessage&&) noexcept = default;
        ISmsAppMessage& operator=(ISmsAppMessage const&) & noexcept = default;
        ISmsAppMessage& operator=(ISmsAppMessage&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsBroadcastMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsBroadcastMessage>,
        impl::require<winrt::Windows::Devices::Sms::ISmsBroadcastMessage, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsBroadcastMessage(std::nullptr_t = nullptr) noexcept {}
        ISmsBroadcastMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsBroadcastMessage(ISmsBroadcastMessage const&) noexcept = default;
        ISmsBroadcastMessage(ISmsBroadcastMessage&&) noexcept = default;
        ISmsBroadcastMessage& operator=(ISmsBroadcastMessage const&) & noexcept = default;
        ISmsBroadcastMessage& operator=(ISmsBroadcastMessage&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsDevice2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsDevice2>
    {
        ISmsDevice2(std::nullptr_t = nullptr) noexcept {}
        ISmsDevice2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsDevice2(ISmsDevice2 const&) noexcept = default;
        ISmsDevice2(ISmsDevice2&&) noexcept = default;
        ISmsDevice2& operator=(ISmsDevice2 const&) & noexcept = default;
        ISmsDevice2& operator=(ISmsDevice2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsDevice2Statics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsDevice2Statics>
    {
        ISmsDevice2Statics(std::nullptr_t = nullptr) noexcept {}
        ISmsDevice2Statics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsDevice2Statics(ISmsDevice2Statics const&) noexcept = default;
        ISmsDevice2Statics(ISmsDevice2Statics&&) noexcept = default;
        ISmsDevice2Statics& operator=(ISmsDevice2Statics const&) & noexcept = default;
        ISmsDevice2Statics& operator=(ISmsDevice2Statics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsFilterRule :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsFilterRule>
    {
        ISmsFilterRule(std::nullptr_t = nullptr) noexcept {}
        ISmsFilterRule(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsFilterRule(ISmsFilterRule const&) noexcept = default;
        ISmsFilterRule(ISmsFilterRule&&) noexcept = default;
        ISmsFilterRule& operator=(ISmsFilterRule const&) & noexcept = default;
        ISmsFilterRule& operator=(ISmsFilterRule&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsFilterRuleFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsFilterRuleFactory>
    {
        ISmsFilterRuleFactory(std::nullptr_t = nullptr) noexcept {}
        ISmsFilterRuleFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsFilterRuleFactory(ISmsFilterRuleFactory const&) noexcept = default;
        ISmsFilterRuleFactory(ISmsFilterRuleFactory&&) noexcept = default;
        ISmsFilterRuleFactory& operator=(ISmsFilterRuleFactory const&) & noexcept = default;
        ISmsFilterRuleFactory& operator=(ISmsFilterRuleFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsFilterRules :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsFilterRules>
    {
        ISmsFilterRules(std::nullptr_t = nullptr) noexcept {}
        ISmsFilterRules(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsFilterRules(ISmsFilterRules const&) noexcept = default;
        ISmsFilterRules(ISmsFilterRules&&) noexcept = default;
        ISmsFilterRules& operator=(ISmsFilterRules const&) & noexcept = default;
        ISmsFilterRules& operator=(ISmsFilterRules&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsFilterRulesFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsFilterRulesFactory>
    {
        ISmsFilterRulesFactory(std::nullptr_t = nullptr) noexcept {}
        ISmsFilterRulesFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsFilterRulesFactory(ISmsFilterRulesFactory const&) noexcept = default;
        ISmsFilterRulesFactory(ISmsFilterRulesFactory&&) noexcept = default;
        ISmsFilterRulesFactory& operator=(ISmsFilterRulesFactory const&) & noexcept = default;
        ISmsFilterRulesFactory& operator=(ISmsFilterRulesFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsMessageBase :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsMessageBase>
    {
        ISmsMessageBase(std::nullptr_t = nullptr) noexcept {}
        ISmsMessageBase(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsMessageBase(ISmsMessageBase const&) noexcept = default;
        ISmsMessageBase(ISmsMessageBase&&) noexcept = default;
        ISmsMessageBase& operator=(ISmsMessageBase const&) & noexcept = default;
        ISmsMessageBase& operator=(ISmsMessageBase&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsMessageReceivedTriggerDetails :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsMessageReceivedTriggerDetails>
    {
        ISmsMessageReceivedTriggerDetails(std::nullptr_t = nullptr) noexcept {}
        ISmsMessageReceivedTriggerDetails(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsMessageReceivedTriggerDetails(ISmsMessageReceivedTriggerDetails const&) noexcept = default;
        ISmsMessageReceivedTriggerDetails(ISmsMessageReceivedTriggerDetails&&) noexcept = default;
        ISmsMessageReceivedTriggerDetails& operator=(ISmsMessageReceivedTriggerDetails const&) & noexcept = default;
        ISmsMessageReceivedTriggerDetails& operator=(ISmsMessageReceivedTriggerDetails&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsMessageRegistration :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsMessageRegistration>
    {
        ISmsMessageRegistration(std::nullptr_t = nullptr) noexcept {}
        ISmsMessageRegistration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsMessageRegistration(ISmsMessageRegistration const&) noexcept = default;
        ISmsMessageRegistration(ISmsMessageRegistration&&) noexcept = default;
        ISmsMessageRegistration& operator=(ISmsMessageRegistration const&) & noexcept = default;
        ISmsMessageRegistration& operator=(ISmsMessageRegistration&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsMessageRegistrationStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsMessageRegistrationStatics>
    {
        ISmsMessageRegistrationStatics(std::nullptr_t = nullptr) noexcept {}
        ISmsMessageRegistrationStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsMessageRegistrationStatics(ISmsMessageRegistrationStatics const&) noexcept = default;
        ISmsMessageRegistrationStatics(ISmsMessageRegistrationStatics&&) noexcept = default;
        ISmsMessageRegistrationStatics& operator=(ISmsMessageRegistrationStatics const&) & noexcept = default;
        ISmsMessageRegistrationStatics& operator=(ISmsMessageRegistrationStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsSendMessageResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsSendMessageResult>
    {
        ISmsSendMessageResult(std::nullptr_t = nullptr) noexcept {}
        ISmsSendMessageResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsSendMessageResult(ISmsSendMessageResult const&) noexcept = default;
        ISmsSendMessageResult(ISmsSendMessageResult&&) noexcept = default;
        ISmsSendMessageResult& operator=(ISmsSendMessageResult const&) & noexcept = default;
        ISmsSendMessageResult& operator=(ISmsSendMessageResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsStatusMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsStatusMessage>,
        impl::require<winrt::Windows::Devices::Sms::ISmsStatusMessage, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsStatusMessage(std::nullptr_t = nullptr) noexcept {}
        ISmsStatusMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsStatusMessage(ISmsStatusMessage const&) noexcept = default;
        ISmsStatusMessage(ISmsStatusMessage&&) noexcept = default;
        ISmsStatusMessage& operator=(ISmsStatusMessage const&) & noexcept = default;
        ISmsStatusMessage& operator=(ISmsStatusMessage&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsTextMessage2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsTextMessage2>,
        impl::require<winrt::Windows::Devices::Sms::ISmsTextMessage2, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsTextMessage2(std::nullptr_t = nullptr) noexcept {}
        ISmsTextMessage2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsTextMessage2(ISmsTextMessage2 const&) noexcept = default;
        ISmsTextMessage2(ISmsTextMessage2&&) noexcept = default;
        ISmsTextMessage2& operator=(ISmsTextMessage2 const&) & noexcept = default;
        ISmsTextMessage2& operator=(ISmsTextMessage2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsVoicemailMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsVoicemailMessage>,
        impl::require<winrt::Windows::Devices::Sms::ISmsVoicemailMessage, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsVoicemailMessage(std::nullptr_t = nullptr) noexcept {}
        ISmsVoicemailMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsVoicemailMessage(ISmsVoicemailMessage const&) noexcept = default;
        ISmsVoicemailMessage(ISmsVoicemailMessage&&) noexcept = default;
        ISmsVoicemailMessage& operator=(ISmsVoicemailMessage const&) & noexcept = default;
        ISmsVoicemailMessage& operator=(ISmsVoicemailMessage&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISmsWapMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISmsWapMessage>,
        impl::require<winrt::Windows::Devices::Sms::ISmsWapMessage, winrt::Windows::Devices::Sms::ISmsMessageBase>
    {
        ISmsWapMessage(std::nullptr_t = nullptr) noexcept {}
        ISmsWapMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISmsWapMessage(ISmsWapMessage const&) noexcept = default;
        ISmsWapMessage(ISmsWapMessage&&) noexcept = default;
        ISmsWapMessage& operator=(ISmsWapMessage const&) & noexcept = default;
        ISmsWapMessage& operator=(ISmsWapMessage&&) & noexcept = default;
    };
}
#endif
