// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_Media_Capture_1_H
#define WINRT_Windows_Media_Capture_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.Storage.Streams.0.h"
#include "winrt/impl/Windows.Media.Capture.0.h"
WINRT_EXPORT namespace winrt::Windows::Media::Capture
{
    struct __declspec(empty_bases) IAdvancedCapturedPhoto :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedCapturedPhoto>
    {
        IAdvancedCapturedPhoto(std::nullptr_t = nullptr) noexcept {}
        IAdvancedCapturedPhoto(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedCapturedPhoto(IAdvancedCapturedPhoto const&) noexcept = default;
        IAdvancedCapturedPhoto(IAdvancedCapturedPhoto&&) noexcept = default;
        IAdvancedCapturedPhoto& operator=(IAdvancedCapturedPhoto const&) & noexcept = default;
        IAdvancedCapturedPhoto& operator=(IAdvancedCapturedPhoto&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAdvancedCapturedPhoto2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedCapturedPhoto2>
    {
        IAdvancedCapturedPhoto2(std::nullptr_t = nullptr) noexcept {}
        IAdvancedCapturedPhoto2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedCapturedPhoto2(IAdvancedCapturedPhoto2 const&) noexcept = default;
        IAdvancedCapturedPhoto2(IAdvancedCapturedPhoto2&&) noexcept = default;
        IAdvancedCapturedPhoto2& operator=(IAdvancedCapturedPhoto2 const&) & noexcept = default;
        IAdvancedCapturedPhoto2& operator=(IAdvancedCapturedPhoto2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAdvancedPhotoCapture :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedPhotoCapture>
    {
        IAdvancedPhotoCapture(std::nullptr_t = nullptr) noexcept {}
        IAdvancedPhotoCapture(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedPhotoCapture(IAdvancedPhotoCapture const&) noexcept = default;
        IAdvancedPhotoCapture(IAdvancedPhotoCapture&&) noexcept = default;
        IAdvancedPhotoCapture& operator=(IAdvancedPhotoCapture const&) & noexcept = default;
        IAdvancedPhotoCapture& operator=(IAdvancedPhotoCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCapture :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapture>
    {
        IAppCapture(std::nullptr_t = nullptr) noexcept {}
        IAppCapture(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapture(IAppCapture const&) noexcept = default;
        IAppCapture(IAppCapture&&) noexcept = default;
        IAppCapture& operator=(IAppCapture const&) & noexcept = default;
        IAppCapture& operator=(IAppCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureStatics>
    {
        IAppCaptureStatics(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureStatics(IAppCaptureStatics const&) noexcept = default;
        IAppCaptureStatics(IAppCaptureStatics&&) noexcept = default;
        IAppCaptureStatics& operator=(IAppCaptureStatics const&) & noexcept = default;
        IAppCaptureStatics& operator=(IAppCaptureStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureStatics2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureStatics2>
    {
        IAppCaptureStatics2(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureStatics2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureStatics2(IAppCaptureStatics2 const&) noexcept = default;
        IAppCaptureStatics2(IAppCaptureStatics2&&) noexcept = default;
        IAppCaptureStatics2& operator=(IAppCaptureStatics2 const&) & noexcept = default;
        IAppCaptureStatics2& operator=(IAppCaptureStatics2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUI :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUI>
    {
        ICameraCaptureUI(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUI(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUI(ICameraCaptureUI const&) noexcept = default;
        ICameraCaptureUI(ICameraCaptureUI&&) noexcept = default;
        ICameraCaptureUI& operator=(ICameraCaptureUI const&) & noexcept = default;
        ICameraCaptureUI& operator=(ICameraCaptureUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUIPhotoCaptureSettings :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUIPhotoCaptureSettings>
    {
        ICameraCaptureUIPhotoCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUIPhotoCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUIPhotoCaptureSettings(ICameraCaptureUIPhotoCaptureSettings const&) noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings(ICameraCaptureUIPhotoCaptureSettings&&) noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings& operator=(ICameraCaptureUIPhotoCaptureSettings const&) & noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings& operator=(ICameraCaptureUIPhotoCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUIVideoCaptureSettings :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUIVideoCaptureSettings>
    {
        ICameraCaptureUIVideoCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUIVideoCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUIVideoCaptureSettings(ICameraCaptureUIVideoCaptureSettings const&) noexcept = default;
        ICameraCaptureUIVideoCaptureSettings(ICameraCaptureUIVideoCaptureSettings&&) noexcept = default;
        ICameraCaptureUIVideoCaptureSettings& operator=(ICameraCaptureUIVideoCaptureSettings const&) & noexcept = default;
        ICameraCaptureUIVideoCaptureSettings& operator=(ICameraCaptureUIVideoCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrame :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrame>,
        impl::require<winrt::Windows::Media::Capture::ICapturedFrame, winrt::Windows::Foundation::IClosable, winrt::Windows::Storage::Streams::IInputStream, winrt::Windows::Storage::Streams::IOutputStream, winrt::Windows::Storage::Streams::IRandomAccessStream, winrt::Windows::Storage::Streams::IContentTypeProvider, winrt::Windows::Storage::Streams::IRandomAccessStreamWithContentType>
    {
        ICapturedFrame(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrame(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrame(ICapturedFrame const&) noexcept = default;
        ICapturedFrame(ICapturedFrame&&) noexcept = default;
        ICapturedFrame& operator=(ICapturedFrame const&) & noexcept = default;
        ICapturedFrame& operator=(ICapturedFrame&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrame2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrame2>
    {
        ICapturedFrame2(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrame2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrame2(ICapturedFrame2 const&) noexcept = default;
        ICapturedFrame2(ICapturedFrame2&&) noexcept = default;
        ICapturedFrame2& operator=(ICapturedFrame2 const&) & noexcept = default;
        ICapturedFrame2& operator=(ICapturedFrame2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameControlValues :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameControlValues>
    {
        ICapturedFrameControlValues(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameControlValues(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameControlValues(ICapturedFrameControlValues const&) noexcept = default;
        ICapturedFrameControlValues(ICapturedFrameControlValues&&) noexcept = default;
        ICapturedFrameControlValues& operator=(ICapturedFrameControlValues const&) & noexcept = default;
        ICapturedFrameControlValues& operator=(ICapturedFrameControlValues&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameControlValues2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameControlValues2>
    {
        ICapturedFrameControlValues2(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameControlValues2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameControlValues2(ICapturedFrameControlValues2 const&) noexcept = default;
        ICapturedFrameControlValues2(ICapturedFrameControlValues2&&) noexcept = default;
        ICapturedFrameControlValues2& operator=(ICapturedFrameControlValues2 const&) & noexcept = default;
        ICapturedFrameControlValues2& operator=(ICapturedFrameControlValues2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameWithSoftwareBitmap :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameWithSoftwareBitmap>
    {
        ICapturedFrameWithSoftwareBitmap(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameWithSoftwareBitmap(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameWithSoftwareBitmap(ICapturedFrameWithSoftwareBitmap const&) noexcept = default;
        ICapturedFrameWithSoftwareBitmap(ICapturedFrameWithSoftwareBitmap&&) noexcept = default;
        ICapturedFrameWithSoftwareBitmap& operator=(ICapturedFrameWithSoftwareBitmap const&) & noexcept = default;
        ICapturedFrameWithSoftwareBitmap& operator=(ICapturedFrameWithSoftwareBitmap&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedPhoto :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedPhoto>
    {
        ICapturedPhoto(std::nullptr_t = nullptr) noexcept {}
        ICapturedPhoto(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedPhoto(ICapturedPhoto const&) noexcept = default;
        ICapturedPhoto(ICapturedPhoto&&) noexcept = default;
        ICapturedPhoto& operator=(ICapturedPhoto const&) & noexcept = default;
        ICapturedPhoto& operator=(ICapturedPhoto&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording>
    {
        ILowLagMediaRecording(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording(ILowLagMediaRecording const&) noexcept = default;
        ILowLagMediaRecording(ILowLagMediaRecording&&) noexcept = default;
        ILowLagMediaRecording& operator=(ILowLagMediaRecording const&) & noexcept = default;
        ILowLagMediaRecording& operator=(ILowLagMediaRecording&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording2>
    {
        ILowLagMediaRecording2(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording2(ILowLagMediaRecording2 const&) noexcept = default;
        ILowLagMediaRecording2(ILowLagMediaRecording2&&) noexcept = default;
        ILowLagMediaRecording2& operator=(ILowLagMediaRecording2 const&) & noexcept = default;
        ILowLagMediaRecording2& operator=(ILowLagMediaRecording2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording3 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording3>
    {
        ILowLagMediaRecording3(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording3(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording3(ILowLagMediaRecording3 const&) noexcept = default;
        ILowLagMediaRecording3(ILowLagMediaRecording3&&) noexcept = default;
        ILowLagMediaRecording3& operator=(ILowLagMediaRecording3 const&) & noexcept = default;
        ILowLagMediaRecording3& operator=(ILowLagMediaRecording3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagPhotoCapture :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagPhotoCapture>
    {
        ILowLagPhotoCapture(std::nullptr_t = nullptr) noexcept {}
        ILowLagPhotoCapture(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagPhotoCapture(ILowLagPhotoCapture const&) noexcept = default;
        ILowLagPhotoCapture(ILowLagPhotoCapture&&) noexcept = default;
        ILowLagPhotoCapture& operator=(ILowLagPhotoCapture const&) & noexcept = default;
        ILowLagPhotoCapture& operator=(ILowLagPhotoCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagPhotoSequenceCapture :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagPhotoSequenceCapture>
    {
        ILowLagPhotoSequenceCapture(std::nullptr_t = nullptr) noexcept {}
        ILowLagPhotoSequenceCapture(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagPhotoSequenceCapture(ILowLagPhotoSequenceCapture const&) noexcept = default;
        ILowLagPhotoSequenceCapture(ILowLagPhotoSequenceCapture&&) noexcept = default;
        ILowLagPhotoSequenceCapture& operator=(ILowLagPhotoSequenceCapture const&) & noexcept = default;
        ILowLagPhotoSequenceCapture& operator=(ILowLagPhotoSequenceCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture>
    {
        IMediaCapture(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture(IMediaCapture const&) noexcept = default;
        IMediaCapture(IMediaCapture&&) noexcept = default;
        IMediaCapture& operator=(IMediaCapture const&) & noexcept = default;
        IMediaCapture& operator=(IMediaCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture2>
    {
        IMediaCapture2(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture2(IMediaCapture2 const&) noexcept = default;
        IMediaCapture2(IMediaCapture2&&) noexcept = default;
        IMediaCapture2& operator=(IMediaCapture2 const&) & noexcept = default;
        IMediaCapture2& operator=(IMediaCapture2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture3 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture3>
    {
        IMediaCapture3(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture3(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture3(IMediaCapture3 const&) noexcept = default;
        IMediaCapture3(IMediaCapture3&&) noexcept = default;
        IMediaCapture3& operator=(IMediaCapture3 const&) & noexcept = default;
        IMediaCapture3& operator=(IMediaCapture3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture4 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture4>
    {
        IMediaCapture4(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture4(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture4(IMediaCapture4 const&) noexcept = default;
        IMediaCapture4(IMediaCapture4&&) noexcept = default;
        IMediaCapture4& operator=(IMediaCapture4 const&) & noexcept = default;
        IMediaCapture4& operator=(IMediaCapture4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture5 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture5>
    {
        IMediaCapture5(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture5(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture5(IMediaCapture5 const&) noexcept = default;
        IMediaCapture5(IMediaCapture5&&) noexcept = default;
        IMediaCapture5& operator=(IMediaCapture5 const&) & noexcept = default;
        IMediaCapture5& operator=(IMediaCapture5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture6 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture6>
    {
        IMediaCapture6(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture6(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture6(IMediaCapture6 const&) noexcept = default;
        IMediaCapture6(IMediaCapture6&&) noexcept = default;
        IMediaCapture6& operator=(IMediaCapture6 const&) & noexcept = default;
        IMediaCapture6& operator=(IMediaCapture6&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture7 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture7>
    {
        IMediaCapture7(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture7(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture7(IMediaCapture7 const&) noexcept = default;
        IMediaCapture7(IMediaCapture7&&) noexcept = default;
        IMediaCapture7& operator=(IMediaCapture7 const&) & noexcept = default;
        IMediaCapture7& operator=(IMediaCapture7&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs>
    {
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs const&) noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs&&) noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs& operator=(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs const&) & noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs& operator=(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureFailedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureFailedEventArgs>
    {
        IMediaCaptureFailedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureFailedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureFailedEventArgs(IMediaCaptureFailedEventArgs const&) noexcept = default;
        IMediaCaptureFailedEventArgs(IMediaCaptureFailedEventArgs&&) noexcept = default;
        IMediaCaptureFailedEventArgs& operator=(IMediaCaptureFailedEventArgs const&) & noexcept = default;
        IMediaCaptureFailedEventArgs& operator=(IMediaCaptureFailedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureFocusChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureFocusChangedEventArgs>
    {
        IMediaCaptureFocusChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureFocusChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureFocusChangedEventArgs(IMediaCaptureFocusChangedEventArgs const&) noexcept = default;
        IMediaCaptureFocusChangedEventArgs(IMediaCaptureFocusChangedEventArgs&&) noexcept = default;
        IMediaCaptureFocusChangedEventArgs& operator=(IMediaCaptureFocusChangedEventArgs const&) & noexcept = default;
        IMediaCaptureFocusChangedEventArgs& operator=(IMediaCaptureFocusChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings>
    {
        IMediaCaptureInitializationSettings(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings(IMediaCaptureInitializationSettings const&) noexcept = default;
        IMediaCaptureInitializationSettings(IMediaCaptureInitializationSettings&&) noexcept = default;
        IMediaCaptureInitializationSettings& operator=(IMediaCaptureInitializationSettings const&) & noexcept = default;
        IMediaCaptureInitializationSettings& operator=(IMediaCaptureInitializationSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings2>
    {
        IMediaCaptureInitializationSettings2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings2(IMediaCaptureInitializationSettings2 const&) noexcept = default;
        IMediaCaptureInitializationSettings2(IMediaCaptureInitializationSettings2&&) noexcept = default;
        IMediaCaptureInitializationSettings2& operator=(IMediaCaptureInitializationSettings2 const&) & noexcept = default;
        IMediaCaptureInitializationSettings2& operator=(IMediaCaptureInitializationSettings2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings3 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings3>
    {
        IMediaCaptureInitializationSettings3(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings3(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings3(IMediaCaptureInitializationSettings3 const&) noexcept = default;
        IMediaCaptureInitializationSettings3(IMediaCaptureInitializationSettings3&&) noexcept = default;
        IMediaCaptureInitializationSettings3& operator=(IMediaCaptureInitializationSettings3 const&) & noexcept = default;
        IMediaCaptureInitializationSettings3& operator=(IMediaCaptureInitializationSettings3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings4 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings4>
    {
        IMediaCaptureInitializationSettings4(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings4(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings4(IMediaCaptureInitializationSettings4 const&) noexcept = default;
        IMediaCaptureInitializationSettings4(IMediaCaptureInitializationSettings4&&) noexcept = default;
        IMediaCaptureInitializationSettings4& operator=(IMediaCaptureInitializationSettings4 const&) & noexcept = default;
        IMediaCaptureInitializationSettings4& operator=(IMediaCaptureInitializationSettings4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings5 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings5>
    {
        IMediaCaptureInitializationSettings5(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings5(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings5(IMediaCaptureInitializationSettings5 const&) noexcept = default;
        IMediaCaptureInitializationSettings5(IMediaCaptureInitializationSettings5&&) noexcept = default;
        IMediaCaptureInitializationSettings5& operator=(IMediaCaptureInitializationSettings5 const&) & noexcept = default;
        IMediaCaptureInitializationSettings5& operator=(IMediaCaptureInitializationSettings5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings6 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings6>
    {
        IMediaCaptureInitializationSettings6(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings6(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings6(IMediaCaptureInitializationSettings6 const&) noexcept = default;
        IMediaCaptureInitializationSettings6(IMediaCaptureInitializationSettings6&&) noexcept = default;
        IMediaCaptureInitializationSettings6& operator=(IMediaCaptureInitializationSettings6 const&) & noexcept = default;
        IMediaCaptureInitializationSettings6& operator=(IMediaCaptureInitializationSettings6&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings7 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings7>
    {
        IMediaCaptureInitializationSettings7(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings7(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings7(IMediaCaptureInitializationSettings7 const&) noexcept = default;
        IMediaCaptureInitializationSettings7(IMediaCaptureInitializationSettings7&&) noexcept = default;
        IMediaCaptureInitializationSettings7& operator=(IMediaCaptureInitializationSettings7 const&) & noexcept = default;
        IMediaCaptureInitializationSettings7& operator=(IMediaCaptureInitializationSettings7&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapturePauseResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapturePauseResult>
    {
        IMediaCapturePauseResult(std::nullptr_t = nullptr) noexcept {}
        IMediaCapturePauseResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapturePauseResult(IMediaCapturePauseResult const&) noexcept = default;
        IMediaCapturePauseResult(IMediaCapturePauseResult&&) noexcept = default;
        IMediaCapturePauseResult& operator=(IMediaCapturePauseResult const&) & noexcept = default;
        IMediaCapturePauseResult& operator=(IMediaCapturePauseResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureRelativePanelWatcher :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureRelativePanelWatcher>
    {
        IMediaCaptureRelativePanelWatcher(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureRelativePanelWatcher(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureRelativePanelWatcher(IMediaCaptureRelativePanelWatcher const&) noexcept = default;
        IMediaCaptureRelativePanelWatcher(IMediaCaptureRelativePanelWatcher&&) noexcept = default;
        IMediaCaptureRelativePanelWatcher& operator=(IMediaCaptureRelativePanelWatcher const&) & noexcept = default;
        IMediaCaptureRelativePanelWatcher& operator=(IMediaCaptureRelativePanelWatcher&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings>
    {
        IMediaCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings(IMediaCaptureSettings const&) noexcept = default;
        IMediaCaptureSettings(IMediaCaptureSettings&&) noexcept = default;
        IMediaCaptureSettings& operator=(IMediaCaptureSettings const&) & noexcept = default;
        IMediaCaptureSettings& operator=(IMediaCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings2>
    {
        IMediaCaptureSettings2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings2(IMediaCaptureSettings2 const&) noexcept = default;
        IMediaCaptureSettings2(IMediaCaptureSettings2&&) noexcept = default;
        IMediaCaptureSettings2& operator=(IMediaCaptureSettings2 const&) & noexcept = default;
        IMediaCaptureSettings2& operator=(IMediaCaptureSettings2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings3 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings3>
    {
        IMediaCaptureSettings3(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings3(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings3(IMediaCaptureSettings3 const&) noexcept = default;
        IMediaCaptureSettings3(IMediaCaptureSettings3&&) noexcept = default;
        IMediaCaptureSettings3& operator=(IMediaCaptureSettings3 const&) & noexcept = default;
        IMediaCaptureSettings3& operator=(IMediaCaptureSettings3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureStatics>
    {
        IMediaCaptureStatics(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureStatics(IMediaCaptureStatics const&) noexcept = default;
        IMediaCaptureStatics(IMediaCaptureStatics&&) noexcept = default;
        IMediaCaptureStatics& operator=(IMediaCaptureStatics const&) & noexcept = default;
        IMediaCaptureStatics& operator=(IMediaCaptureStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureStopResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureStopResult>
    {
        IMediaCaptureStopResult(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureStopResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureStopResult(IMediaCaptureStopResult const&) noexcept = default;
        IMediaCaptureStopResult(IMediaCaptureStopResult&&) noexcept = default;
        IMediaCaptureStopResult& operator=(IMediaCaptureStopResult const&) & noexcept = default;
        IMediaCaptureStopResult& operator=(IMediaCaptureStopResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoPreview :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoPreview>
    {
        IMediaCaptureVideoPreview(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoPreview(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoPreview(IMediaCaptureVideoPreview const&) noexcept = default;
        IMediaCaptureVideoPreview(IMediaCaptureVideoPreview&&) noexcept = default;
        IMediaCaptureVideoPreview& operator=(IMediaCaptureVideoPreview const&) & noexcept = default;
        IMediaCaptureVideoPreview& operator=(IMediaCaptureVideoPreview&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfile :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfile>
    {
        IMediaCaptureVideoProfile(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfile(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfile(IMediaCaptureVideoProfile const&) noexcept = default;
        IMediaCaptureVideoProfile(IMediaCaptureVideoProfile&&) noexcept = default;
        IMediaCaptureVideoProfile& operator=(IMediaCaptureVideoProfile const&) & noexcept = default;
        IMediaCaptureVideoProfile& operator=(IMediaCaptureVideoProfile&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfile2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfile2>
    {
        IMediaCaptureVideoProfile2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfile2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfile2(IMediaCaptureVideoProfile2 const&) noexcept = default;
        IMediaCaptureVideoProfile2(IMediaCaptureVideoProfile2&&) noexcept = default;
        IMediaCaptureVideoProfile2& operator=(IMediaCaptureVideoProfile2 const&) & noexcept = default;
        IMediaCaptureVideoProfile2& operator=(IMediaCaptureVideoProfile2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfileMediaDescription :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfileMediaDescription>
    {
        IMediaCaptureVideoProfileMediaDescription(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfileMediaDescription(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfileMediaDescription(IMediaCaptureVideoProfileMediaDescription const&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription(IMediaCaptureVideoProfileMediaDescription&&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription& operator=(IMediaCaptureVideoProfileMediaDescription const&) & noexcept = default;
        IMediaCaptureVideoProfileMediaDescription& operator=(IMediaCaptureVideoProfileMediaDescription&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfileMediaDescription2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfileMediaDescription2>
    {
        IMediaCaptureVideoProfileMediaDescription2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfileMediaDescription2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfileMediaDescription2(IMediaCaptureVideoProfileMediaDescription2 const&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2(IMediaCaptureVideoProfileMediaDescription2&&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2& operator=(IMediaCaptureVideoProfileMediaDescription2 const&) & noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2& operator=(IMediaCaptureVideoProfileMediaDescription2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IOptionalReferencePhotoCapturedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IOptionalReferencePhotoCapturedEventArgs>
    {
        IOptionalReferencePhotoCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IOptionalReferencePhotoCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IOptionalReferencePhotoCapturedEventArgs(IOptionalReferencePhotoCapturedEventArgs const&) noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs(IOptionalReferencePhotoCapturedEventArgs&&) noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs& operator=(IOptionalReferencePhotoCapturedEventArgs const&) & noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs& operator=(IOptionalReferencePhotoCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPhotoCapturedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPhotoCapturedEventArgs>
    {
        IPhotoCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPhotoCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPhotoCapturedEventArgs(IPhotoCapturedEventArgs const&) noexcept = default;
        IPhotoCapturedEventArgs(IPhotoCapturedEventArgs&&) noexcept = default;
        IPhotoCapturedEventArgs& operator=(IPhotoCapturedEventArgs const&) & noexcept = default;
        IPhotoCapturedEventArgs& operator=(IPhotoCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPhotoConfirmationCapturedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPhotoConfirmationCapturedEventArgs>
    {
        IPhotoConfirmationCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPhotoConfirmationCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPhotoConfirmationCapturedEventArgs(IPhotoConfirmationCapturedEventArgs const&) noexcept = default;
        IPhotoConfirmationCapturedEventArgs(IPhotoConfirmationCapturedEventArgs&&) noexcept = default;
        IPhotoConfirmationCapturedEventArgs& operator=(IPhotoConfirmationCapturedEventArgs const&) & noexcept = default;
        IPhotoConfirmationCapturedEventArgs& operator=(IPhotoConfirmationCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IVideoStreamConfiguration :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IVideoStreamConfiguration>
    {
        IVideoStreamConfiguration(std::nullptr_t = nullptr) noexcept {}
        IVideoStreamConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IVideoStreamConfiguration(IVideoStreamConfiguration const&) noexcept = default;
        IVideoStreamConfiguration(IVideoStreamConfiguration&&) noexcept = default;
        IVideoStreamConfiguration& operator=(IVideoStreamConfiguration const&) & noexcept = default;
        IVideoStreamConfiguration& operator=(IVideoStreamConfiguration&&) & noexcept = default;
    };
}
#endif
