// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_ApplicationModel_Activation_2_H
#define WINRT_Windows_ApplicationModel_Activation_2_H
#include "winrt/impl/Windows.ApplicationModel.Activation.1.h"
WINRT_EXPORT namespace winrt::Windows::ApplicationModel::Activation
{
    struct __declspec(empty_bases) AppointmentsProviderAddAppointmentActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderAddAppointmentActivatedEventArgs,
        impl::require<AppointmentsProviderAddAppointmentActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        AppointmentsProviderAddAppointmentActivatedEventArgs(std::nullptr_t) noexcept {}
        AppointmentsProviderAddAppointmentActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderAddAppointmentActivatedEventArgs(ptr, take_ownership_from_abi) {}
        AppointmentsProviderAddAppointmentActivatedEventArgs(AppointmentsProviderAddAppointmentActivatedEventArgs const&) noexcept = default;
        AppointmentsProviderAddAppointmentActivatedEventArgs(AppointmentsProviderAddAppointmentActivatedEventArgs&&) noexcept = default;
        AppointmentsProviderAddAppointmentActivatedEventArgs& operator=(AppointmentsProviderAddAppointmentActivatedEventArgs const&) & noexcept = default;
        AppointmentsProviderAddAppointmentActivatedEventArgs& operator=(AppointmentsProviderAddAppointmentActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) AppointmentsProviderRemoveAppointmentActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderRemoveAppointmentActivatedEventArgs,
        impl::require<AppointmentsProviderRemoveAppointmentActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        AppointmentsProviderRemoveAppointmentActivatedEventArgs(std::nullptr_t) noexcept {}
        AppointmentsProviderRemoveAppointmentActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderRemoveAppointmentActivatedEventArgs(ptr, take_ownership_from_abi) {}
        AppointmentsProviderRemoveAppointmentActivatedEventArgs(AppointmentsProviderRemoveAppointmentActivatedEventArgs const&) noexcept = default;
        AppointmentsProviderRemoveAppointmentActivatedEventArgs(AppointmentsProviderRemoveAppointmentActivatedEventArgs&&) noexcept = default;
        AppointmentsProviderRemoveAppointmentActivatedEventArgs& operator=(AppointmentsProviderRemoveAppointmentActivatedEventArgs const&) & noexcept = default;
        AppointmentsProviderRemoveAppointmentActivatedEventArgs& operator=(AppointmentsProviderRemoveAppointmentActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) AppointmentsProviderReplaceAppointmentActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderReplaceAppointmentActivatedEventArgs,
        impl::require<AppointmentsProviderReplaceAppointmentActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        AppointmentsProviderReplaceAppointmentActivatedEventArgs(std::nullptr_t) noexcept {}
        AppointmentsProviderReplaceAppointmentActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderReplaceAppointmentActivatedEventArgs(ptr, take_ownership_from_abi) {}
        AppointmentsProviderReplaceAppointmentActivatedEventArgs(AppointmentsProviderReplaceAppointmentActivatedEventArgs const&) noexcept = default;
        AppointmentsProviderReplaceAppointmentActivatedEventArgs(AppointmentsProviderReplaceAppointmentActivatedEventArgs&&) noexcept = default;
        AppointmentsProviderReplaceAppointmentActivatedEventArgs& operator=(AppointmentsProviderReplaceAppointmentActivatedEventArgs const&) & noexcept = default;
        AppointmentsProviderReplaceAppointmentActivatedEventArgs& operator=(AppointmentsProviderReplaceAppointmentActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) AppointmentsProviderShowAppointmentDetailsActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderShowAppointmentDetailsActivatedEventArgs,
        impl::require<AppointmentsProviderShowAppointmentDetailsActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs(std::nullptr_t) noexcept {}
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderShowAppointmentDetailsActivatedEventArgs(ptr, take_ownership_from_abi) {}
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs(AppointmentsProviderShowAppointmentDetailsActivatedEventArgs const&) noexcept = default;
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs(AppointmentsProviderShowAppointmentDetailsActivatedEventArgs&&) noexcept = default;
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs& operator=(AppointmentsProviderShowAppointmentDetailsActivatedEventArgs const&) & noexcept = default;
        AppointmentsProviderShowAppointmentDetailsActivatedEventArgs& operator=(AppointmentsProviderShowAppointmentDetailsActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) AppointmentsProviderShowTimeFrameActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderShowTimeFrameActivatedEventArgs,
        impl::require<AppointmentsProviderShowTimeFrameActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        AppointmentsProviderShowTimeFrameActivatedEventArgs(std::nullptr_t) noexcept {}
        AppointmentsProviderShowTimeFrameActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IAppointmentsProviderShowTimeFrameActivatedEventArgs(ptr, take_ownership_from_abi) {}
        AppointmentsProviderShowTimeFrameActivatedEventArgs(AppointmentsProviderShowTimeFrameActivatedEventArgs const&) noexcept = default;
        AppointmentsProviderShowTimeFrameActivatedEventArgs(AppointmentsProviderShowTimeFrameActivatedEventArgs&&) noexcept = default;
        AppointmentsProviderShowTimeFrameActivatedEventArgs& operator=(AppointmentsProviderShowTimeFrameActivatedEventArgs const&) & noexcept = default;
        AppointmentsProviderShowTimeFrameActivatedEventArgs& operator=(AppointmentsProviderShowTimeFrameActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) BackgroundActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IBackgroundActivatedEventArgs
    {
        BackgroundActivatedEventArgs(std::nullptr_t) noexcept {}
        BackgroundActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IBackgroundActivatedEventArgs(ptr, take_ownership_from_abi) {}
        BackgroundActivatedEventArgs(BackgroundActivatedEventArgs const&) noexcept = default;
        BackgroundActivatedEventArgs(BackgroundActivatedEventArgs&&) noexcept = default;
        BackgroundActivatedEventArgs& operator=(BackgroundActivatedEventArgs const&) & noexcept = default;
        BackgroundActivatedEventArgs& operator=(BackgroundActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) BarcodeScannerPreviewActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IBarcodeScannerPreviewActivatedEventArgs,
        impl::require<BarcodeScannerPreviewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        BarcodeScannerPreviewActivatedEventArgs(std::nullptr_t) noexcept {}
        BarcodeScannerPreviewActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IBarcodeScannerPreviewActivatedEventArgs(ptr, take_ownership_from_abi) {}
        BarcodeScannerPreviewActivatedEventArgs(BarcodeScannerPreviewActivatedEventArgs const&) noexcept = default;
        BarcodeScannerPreviewActivatedEventArgs(BarcodeScannerPreviewActivatedEventArgs&&) noexcept = default;
        BarcodeScannerPreviewActivatedEventArgs& operator=(BarcodeScannerPreviewActivatedEventArgs const&) & noexcept = default;
        BarcodeScannerPreviewActivatedEventArgs& operator=(BarcodeScannerPreviewActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) CachedFileUpdaterActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::ICachedFileUpdaterActivatedEventArgs,
        impl::require<CachedFileUpdaterActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        CachedFileUpdaterActivatedEventArgs(std::nullptr_t) noexcept {}
        CachedFileUpdaterActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ICachedFileUpdaterActivatedEventArgs(ptr, take_ownership_from_abi) {}
        CachedFileUpdaterActivatedEventArgs(CachedFileUpdaterActivatedEventArgs const&) noexcept = default;
        CachedFileUpdaterActivatedEventArgs(CachedFileUpdaterActivatedEventArgs&&) noexcept = default;
        CachedFileUpdaterActivatedEventArgs& operator=(CachedFileUpdaterActivatedEventArgs const&) & noexcept = default;
        CachedFileUpdaterActivatedEventArgs& operator=(CachedFileUpdaterActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) CommandLineActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::ICommandLineActivatedEventArgs,
        impl::require<CommandLineActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        CommandLineActivatedEventArgs(std::nullptr_t) noexcept {}
        CommandLineActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ICommandLineActivatedEventArgs(ptr, take_ownership_from_abi) {}
        CommandLineActivatedEventArgs(CommandLineActivatedEventArgs const&) noexcept = default;
        CommandLineActivatedEventArgs(CommandLineActivatedEventArgs&&) noexcept = default;
        CommandLineActivatedEventArgs& operator=(CommandLineActivatedEventArgs const&) & noexcept = default;
        CommandLineActivatedEventArgs& operator=(CommandLineActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) CommandLineActivationOperation : winrt::Windows::ApplicationModel::Activation::ICommandLineActivationOperation
    {
        CommandLineActivationOperation(std::nullptr_t) noexcept {}
        CommandLineActivationOperation(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ICommandLineActivationOperation(ptr, take_ownership_from_abi) {}
        CommandLineActivationOperation(CommandLineActivationOperation const&) noexcept = default;
        CommandLineActivationOperation(CommandLineActivationOperation&&) noexcept = default;
        CommandLineActivationOperation& operator=(CommandLineActivationOperation const&) & noexcept = default;
        CommandLineActivationOperation& operator=(CommandLineActivationOperation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ContactPanelActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IContactPanelActivatedEventArgs,
        impl::require<ContactPanelActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        ContactPanelActivatedEventArgs(std::nullptr_t) noexcept {}
        ContactPanelActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IContactPanelActivatedEventArgs(ptr, take_ownership_from_abi) {}
        ContactPanelActivatedEventArgs(ContactPanelActivatedEventArgs const&) noexcept = default;
        ContactPanelActivatedEventArgs(ContactPanelActivatedEventArgs&&) noexcept = default;
        ContactPanelActivatedEventArgs& operator=(ContactPanelActivatedEventArgs const&) & noexcept = default;
        ContactPanelActivatedEventArgs& operator=(ContactPanelActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) DeviceActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IDeviceActivatedEventArgs,
        impl::require<DeviceActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        DeviceActivatedEventArgs(std::nullptr_t) noexcept {}
        DeviceActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IDeviceActivatedEventArgs(ptr, take_ownership_from_abi) {}
        DeviceActivatedEventArgs(DeviceActivatedEventArgs const&) noexcept = default;
        DeviceActivatedEventArgs(DeviceActivatedEventArgs&&) noexcept = default;
        DeviceActivatedEventArgs& operator=(DeviceActivatedEventArgs const&) & noexcept = default;
        DeviceActivatedEventArgs& operator=(DeviceActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) DevicePairingActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IDevicePairingActivatedEventArgs,
        impl::require<DevicePairingActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        DevicePairingActivatedEventArgs(std::nullptr_t) noexcept {}
        DevicePairingActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IDevicePairingActivatedEventArgs(ptr, take_ownership_from_abi) {}
        DevicePairingActivatedEventArgs(DevicePairingActivatedEventArgs const&) noexcept = default;
        DevicePairingActivatedEventArgs(DevicePairingActivatedEventArgs&&) noexcept = default;
        DevicePairingActivatedEventArgs& operator=(DevicePairingActivatedEventArgs const&) & noexcept = default;
        DevicePairingActivatedEventArgs& operator=(DevicePairingActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) DialReceiverActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IDialReceiverActivatedEventArgs,
        impl::require<DialReceiverActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        DialReceiverActivatedEventArgs(std::nullptr_t) noexcept {}
        DialReceiverActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IDialReceiverActivatedEventArgs(ptr, take_ownership_from_abi) {}
        DialReceiverActivatedEventArgs(DialReceiverActivatedEventArgs const&) noexcept = default;
        DialReceiverActivatedEventArgs(DialReceiverActivatedEventArgs&&) noexcept = default;
        DialReceiverActivatedEventArgs& operator=(DialReceiverActivatedEventArgs const&) & noexcept = default;
        DialReceiverActivatedEventArgs& operator=(DialReceiverActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IFileActivatedEventArgs,
        impl::require<FileActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IFileActivatedEventArgsWithNeighboringFiles, winrt::Windows::ApplicationModel::Activation::IFileActivatedEventArgsWithCallerPackageFamilyName, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FileActivatedEventArgs(std::nullptr_t) noexcept {}
        FileActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFileActivatedEventArgs(ptr, take_ownership_from_abi) {}
        FileActivatedEventArgs(FileActivatedEventArgs const&) noexcept = default;
        FileActivatedEventArgs(FileActivatedEventArgs&&) noexcept = default;
        FileActivatedEventArgs& operator=(FileActivatedEventArgs const&) & noexcept = default;
        FileActivatedEventArgs& operator=(FileActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileOpenPickerActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IFileOpenPickerActivatedEventArgs,
        impl::require<FileOpenPickerActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IFileOpenPickerActivatedEventArgs2, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FileOpenPickerActivatedEventArgs(std::nullptr_t) noexcept {}
        FileOpenPickerActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFileOpenPickerActivatedEventArgs(ptr, take_ownership_from_abi) {}
        FileOpenPickerActivatedEventArgs(FileOpenPickerActivatedEventArgs const&) noexcept = default;
        FileOpenPickerActivatedEventArgs(FileOpenPickerActivatedEventArgs&&) noexcept = default;
        FileOpenPickerActivatedEventArgs& operator=(FileOpenPickerActivatedEventArgs const&) & noexcept = default;
        FileOpenPickerActivatedEventArgs& operator=(FileOpenPickerActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileOpenPickerContinuationEventArgs : winrt::Windows::ApplicationModel::Activation::IFileOpenPickerContinuationEventArgs,
        impl::require<FileOpenPickerContinuationEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FileOpenPickerContinuationEventArgs(std::nullptr_t) noexcept {}
        FileOpenPickerContinuationEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFileOpenPickerContinuationEventArgs(ptr, take_ownership_from_abi) {}
        FileOpenPickerContinuationEventArgs(FileOpenPickerContinuationEventArgs const&) noexcept = default;
        FileOpenPickerContinuationEventArgs(FileOpenPickerContinuationEventArgs&&) noexcept = default;
        FileOpenPickerContinuationEventArgs& operator=(FileOpenPickerContinuationEventArgs const&) & noexcept = default;
        FileOpenPickerContinuationEventArgs& operator=(FileOpenPickerContinuationEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileSavePickerActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IFileSavePickerActivatedEventArgs,
        impl::require<FileSavePickerActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IFileSavePickerActivatedEventArgs2, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FileSavePickerActivatedEventArgs(std::nullptr_t) noexcept {}
        FileSavePickerActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFileSavePickerActivatedEventArgs(ptr, take_ownership_from_abi) {}
        FileSavePickerActivatedEventArgs(FileSavePickerActivatedEventArgs const&) noexcept = default;
        FileSavePickerActivatedEventArgs(FileSavePickerActivatedEventArgs&&) noexcept = default;
        FileSavePickerActivatedEventArgs& operator=(FileSavePickerActivatedEventArgs const&) & noexcept = default;
        FileSavePickerActivatedEventArgs& operator=(FileSavePickerActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileSavePickerContinuationEventArgs : winrt::Windows::ApplicationModel::Activation::IFileSavePickerContinuationEventArgs,
        impl::require<FileSavePickerContinuationEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FileSavePickerContinuationEventArgs(std::nullptr_t) noexcept {}
        FileSavePickerContinuationEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFileSavePickerContinuationEventArgs(ptr, take_ownership_from_abi) {}
        FileSavePickerContinuationEventArgs(FileSavePickerContinuationEventArgs const&) noexcept = default;
        FileSavePickerContinuationEventArgs(FileSavePickerContinuationEventArgs&&) noexcept = default;
        FileSavePickerContinuationEventArgs& operator=(FileSavePickerContinuationEventArgs const&) & noexcept = default;
        FileSavePickerContinuationEventArgs& operator=(FileSavePickerContinuationEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FolderPickerContinuationEventArgs : winrt::Windows::ApplicationModel::Activation::IFolderPickerContinuationEventArgs,
        impl::require<FolderPickerContinuationEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        FolderPickerContinuationEventArgs(std::nullptr_t) noexcept {}
        FolderPickerContinuationEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IFolderPickerContinuationEventArgs(ptr, take_ownership_from_abi) {}
        FolderPickerContinuationEventArgs(FolderPickerContinuationEventArgs const&) noexcept = default;
        FolderPickerContinuationEventArgs(FolderPickerContinuationEventArgs&&) noexcept = default;
        FolderPickerContinuationEventArgs& operator=(FolderPickerContinuationEventArgs const&) & noexcept = default;
        FolderPickerContinuationEventArgs& operator=(FolderPickerContinuationEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) LaunchActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::ILaunchActivatedEventArgs,
        impl::require<LaunchActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IPrelaunchActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::ILaunchActivatedEventArgs2, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        LaunchActivatedEventArgs(std::nullptr_t) noexcept {}
        LaunchActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ILaunchActivatedEventArgs(ptr, take_ownership_from_abi) {}
        LaunchActivatedEventArgs(LaunchActivatedEventArgs const&) noexcept = default;
        LaunchActivatedEventArgs(LaunchActivatedEventArgs&&) noexcept = default;
        LaunchActivatedEventArgs& operator=(LaunchActivatedEventArgs const&) & noexcept = default;
        LaunchActivatedEventArgs& operator=(LaunchActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) LockScreenActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::ILockScreenActivatedEventArgs,
        impl::require<LockScreenActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        LockScreenActivatedEventArgs(std::nullptr_t) noexcept {}
        LockScreenActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ILockScreenActivatedEventArgs(ptr, take_ownership_from_abi) {}
        LockScreenActivatedEventArgs(LockScreenActivatedEventArgs const&) noexcept = default;
        LockScreenActivatedEventArgs(LockScreenActivatedEventArgs&&) noexcept = default;
        LockScreenActivatedEventArgs& operator=(LockScreenActivatedEventArgs const&) & noexcept = default;
        LockScreenActivatedEventArgs& operator=(LockScreenActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) LockScreenComponentActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs
    {
        LockScreenComponentActivatedEventArgs(std::nullptr_t) noexcept {}
        LockScreenComponentActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs(ptr, take_ownership_from_abi) {}
        LockScreenComponentActivatedEventArgs(LockScreenComponentActivatedEventArgs const&) noexcept = default;
        LockScreenComponentActivatedEventArgs(LockScreenComponentActivatedEventArgs&&) noexcept = default;
        LockScreenComponentActivatedEventArgs& operator=(LockScreenComponentActivatedEventArgs const&) & noexcept = default;
        LockScreenComponentActivatedEventArgs& operator=(LockScreenComponentActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) PickerReturnedActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IPickerReturnedActivatedEventArgs
    {
        PickerReturnedActivatedEventArgs(std::nullptr_t) noexcept {}
        PickerReturnedActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IPickerReturnedActivatedEventArgs(ptr, take_ownership_from_abi) {}
        PickerReturnedActivatedEventArgs(PickerReturnedActivatedEventArgs const&) noexcept = default;
        PickerReturnedActivatedEventArgs(PickerReturnedActivatedEventArgs&&) noexcept = default;
        PickerReturnedActivatedEventArgs& operator=(PickerReturnedActivatedEventArgs const&) & noexcept = default;
        PickerReturnedActivatedEventArgs& operator=(PickerReturnedActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ProtocolActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgs,
        impl::require<ProtocolActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgsWithCallerPackageFamilyNameAndData, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        ProtocolActivatedEventArgs(std::nullptr_t) noexcept {}
        ProtocolActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgs(ptr, take_ownership_from_abi) {}
        ProtocolActivatedEventArgs(ProtocolActivatedEventArgs const&) noexcept = default;
        ProtocolActivatedEventArgs(ProtocolActivatedEventArgs&&) noexcept = default;
        ProtocolActivatedEventArgs& operator=(ProtocolActivatedEventArgs const&) & noexcept = default;
        ProtocolActivatedEventArgs& operator=(ProtocolActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ProtocolForResultsActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IProtocolForResultsActivatedEventArgs,
        impl::require<ProtocolForResultsActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgsWithCallerPackageFamilyNameAndData, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        ProtocolForResultsActivatedEventArgs(std::nullptr_t) noexcept {}
        ProtocolForResultsActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IProtocolForResultsActivatedEventArgs(ptr, take_ownership_from_abi) {}
        ProtocolForResultsActivatedEventArgs(ProtocolForResultsActivatedEventArgs const&) noexcept = default;
        ProtocolForResultsActivatedEventArgs(ProtocolForResultsActivatedEventArgs&&) noexcept = default;
        ProtocolForResultsActivatedEventArgs& operator=(ProtocolForResultsActivatedEventArgs const&) & noexcept = default;
        ProtocolForResultsActivatedEventArgs& operator=(ProtocolForResultsActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) RestrictedLaunchActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IRestrictedLaunchActivatedEventArgs,
        impl::require<RestrictedLaunchActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        RestrictedLaunchActivatedEventArgs(std::nullptr_t) noexcept {}
        RestrictedLaunchActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IRestrictedLaunchActivatedEventArgs(ptr, take_ownership_from_abi) {}
        RestrictedLaunchActivatedEventArgs(RestrictedLaunchActivatedEventArgs const&) noexcept = default;
        RestrictedLaunchActivatedEventArgs(RestrictedLaunchActivatedEventArgs&&) noexcept = default;
        RestrictedLaunchActivatedEventArgs& operator=(RestrictedLaunchActivatedEventArgs const&) & noexcept = default;
        RestrictedLaunchActivatedEventArgs& operator=(RestrictedLaunchActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) SearchActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::ISearchActivatedEventArgs,
        impl::require<SearchActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::ISearchActivatedEventArgsWithLinguisticDetails, winrt::Windows::ApplicationModel::Activation::IViewSwitcherProvider, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        SearchActivatedEventArgs(std::nullptr_t) noexcept {}
        SearchActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ISearchActivatedEventArgs(ptr, take_ownership_from_abi) {}
        SearchActivatedEventArgs(SearchActivatedEventArgs const&) noexcept = default;
        SearchActivatedEventArgs(SearchActivatedEventArgs&&) noexcept = default;
        SearchActivatedEventArgs& operator=(SearchActivatedEventArgs const&) & noexcept = default;
        SearchActivatedEventArgs& operator=(SearchActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ShareTargetActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IShareTargetActivatedEventArgs,
        impl::require<ShareTargetActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        ShareTargetActivatedEventArgs(std::nullptr_t) noexcept {}
        ShareTargetActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IShareTargetActivatedEventArgs(ptr, take_ownership_from_abi) {}
        ShareTargetActivatedEventArgs(ShareTargetActivatedEventArgs const&) noexcept = default;
        ShareTargetActivatedEventArgs(ShareTargetActivatedEventArgs&&) noexcept = default;
        ShareTargetActivatedEventArgs& operator=(ShareTargetActivatedEventArgs const&) & noexcept = default;
        ShareTargetActivatedEventArgs& operator=(ShareTargetActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) SplashScreen : winrt::Windows::ApplicationModel::Activation::ISplashScreen
    {
        SplashScreen(std::nullptr_t) noexcept {}
        SplashScreen(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ISplashScreen(ptr, take_ownership_from_abi) {}
        SplashScreen(SplashScreen const&) noexcept = default;
        SplashScreen(SplashScreen&&) noexcept = default;
        SplashScreen& operator=(SplashScreen const&) & noexcept = default;
        SplashScreen& operator=(SplashScreen&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StartupTaskActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IStartupTaskActivatedEventArgs,
        impl::require<StartupTaskActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        StartupTaskActivatedEventArgs(std::nullptr_t) noexcept {}
        StartupTaskActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IStartupTaskActivatedEventArgs(ptr, take_ownership_from_abi) {}
        StartupTaskActivatedEventArgs(StartupTaskActivatedEventArgs const&) noexcept = default;
        StartupTaskActivatedEventArgs(StartupTaskActivatedEventArgs&&) noexcept = default;
        StartupTaskActivatedEventArgs& operator=(StartupTaskActivatedEventArgs const&) & noexcept = default;
        StartupTaskActivatedEventArgs& operator=(StartupTaskActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) TileActivatedInfo : winrt::Windows::ApplicationModel::Activation::ITileActivatedInfo
    {
        TileActivatedInfo(std::nullptr_t) noexcept {}
        TileActivatedInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::ITileActivatedInfo(ptr, take_ownership_from_abi) {}
        TileActivatedInfo(TileActivatedInfo const&) noexcept = default;
        TileActivatedInfo(TileActivatedInfo&&) noexcept = default;
        TileActivatedInfo& operator=(TileActivatedInfo const&) & noexcept = default;
        TileActivatedInfo& operator=(TileActivatedInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ToastNotificationActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IToastNotificationActivatedEventArgs,
        impl::require<ToastNotificationActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser, winrt::Windows::ApplicationModel::Activation::IApplicationViewActivatedEventArgs>
    {
        ToastNotificationActivatedEventArgs(std::nullptr_t) noexcept {}
        ToastNotificationActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IToastNotificationActivatedEventArgs(ptr, take_ownership_from_abi) {}
        ToastNotificationActivatedEventArgs(ToastNotificationActivatedEventArgs const&) noexcept = default;
        ToastNotificationActivatedEventArgs(ToastNotificationActivatedEventArgs&&) noexcept = default;
        ToastNotificationActivatedEventArgs& operator=(ToastNotificationActivatedEventArgs const&) & noexcept = default;
        ToastNotificationActivatedEventArgs& operator=(ToastNotificationActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) UserDataAccountProviderActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IUserDataAccountProviderActivatedEventArgs
    {
        UserDataAccountProviderActivatedEventArgs(std::nullptr_t) noexcept {}
        UserDataAccountProviderActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IUserDataAccountProviderActivatedEventArgs(ptr, take_ownership_from_abi) {}
        UserDataAccountProviderActivatedEventArgs(UserDataAccountProviderActivatedEventArgs const&) noexcept = default;
        UserDataAccountProviderActivatedEventArgs(UserDataAccountProviderActivatedEventArgs&&) noexcept = default;
        UserDataAccountProviderActivatedEventArgs& operator=(UserDataAccountProviderActivatedEventArgs const&) & noexcept = default;
        UserDataAccountProviderActivatedEventArgs& operator=(UserDataAccountProviderActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) VoiceCommandActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IVoiceCommandActivatedEventArgs,
        impl::require<VoiceCommandActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        VoiceCommandActivatedEventArgs(std::nullptr_t) noexcept {}
        VoiceCommandActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IVoiceCommandActivatedEventArgs(ptr, take_ownership_from_abi) {}
        VoiceCommandActivatedEventArgs(VoiceCommandActivatedEventArgs const&) noexcept = default;
        VoiceCommandActivatedEventArgs(VoiceCommandActivatedEventArgs&&) noexcept = default;
        VoiceCommandActivatedEventArgs& operator=(VoiceCommandActivatedEventArgs const&) & noexcept = default;
        VoiceCommandActivatedEventArgs& operator=(VoiceCommandActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WebAccountProviderActivatedEventArgs : winrt::Windows::ApplicationModel::Activation::IWebAccountProviderActivatedEventArgs,
        impl::require<WebAccountProviderActivatedEventArgs, winrt::Windows::ApplicationModel::Activation::IActivatedEventArgsWithUser>
    {
        WebAccountProviderActivatedEventArgs(std::nullptr_t) noexcept {}
        WebAccountProviderActivatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IWebAccountProviderActivatedEventArgs(ptr, take_ownership_from_abi) {}
        WebAccountProviderActivatedEventArgs(WebAccountProviderActivatedEventArgs const&) noexcept = default;
        WebAccountProviderActivatedEventArgs(WebAccountProviderActivatedEventArgs&&) noexcept = default;
        WebAccountProviderActivatedEventArgs& operator=(WebAccountProviderActivatedEventArgs const&) & noexcept = default;
        WebAccountProviderActivatedEventArgs& operator=(WebAccountProviderActivatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) WebAuthenticationBrokerContinuationEventArgs : winrt::Windows::ApplicationModel::Activation::IWebAuthenticationBrokerContinuationEventArgs
    {
        WebAuthenticationBrokerContinuationEventArgs(std::nullptr_t) noexcept {}
        WebAuthenticationBrokerContinuationEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Activation::IWebAuthenticationBrokerContinuationEventArgs(ptr, take_ownership_from_abi) {}
        WebAuthenticationBrokerContinuationEventArgs(WebAuthenticationBrokerContinuationEventArgs const&) noexcept = default;
        WebAuthenticationBrokerContinuationEventArgs(WebAuthenticationBrokerContinuationEventArgs&&) noexcept = default;
        WebAuthenticationBrokerContinuationEventArgs& operator=(WebAuthenticationBrokerContinuationEventArgs const&) & noexcept = default;
        WebAuthenticationBrokerContinuationEventArgs& operator=(WebAuthenticationBrokerContinuationEventArgs&&) & noexcept = default;
    };
}
#endif
