// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210505.3

#ifndef WINRT_Windows_Security_EnterpriseData_1_H
#define WINRT_Windows_Security_EnterpriseData_1_H
#include "winrt/impl/Windows.Security.EnterpriseData.0.h"
WINRT_EXPORT namespace winrt::Windows::Security::EnterpriseData
{
}
#endif
